version: '3.1'

services:
db:
    image: mongo:4.0.27
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecosister-username
      MONGO_INITDB_ROOT_PASSWORD: ecosister-password
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_init/data:/tmp/data
      - ./db_data:/data/db  # Persistent data storage
    ports:
      - "27017:27017"
