version: "3.1"

services:
  routes-service:
    image: sdg97/ecosister-routes-service:latest
    ports:
      - "5000:5000"
    depends_on:
      - aq-service
    environment:
      AQ_SERVICE_INTERPOLATE_API: "http://aq-service:5000/interpolate"

  aq-service:
    image: sdg97/ecosister-aq-service:latest
    ports:
      - "5001:5000"

  users-service:
    image: sdg97/ecosister-users-service:latest
    ports:
      - "5003:5000"
    depends_on:
      - db
    environment:
      PROD: "true"
      MONGO_URI: "mongodb://ecosister-username:ecosister-password@db:27017/?authMechanism=DEFAULT" # Adjust as needed
      SECRET_KEY: "your-prod-secret"
      JWT_SECRET_KEY: "your-prod-jwt-secret"

  db:
    image: mongo:4.0.27
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: ecosister-username
      MONGO_INITDB_ROOT_PASSWORD: ecosister-password
    volumes:
      - ./db_init:/docker-entrypoint-initdb.d
      - ./db_init/data:/tmp/data
      - ./db_data:/data/db # Persistent data storage
    ports:
      - "27017:27017"

  nginx:
    image: nginx:latest
    ports:
      - "80:5002"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./build:/usr/share/nginx/html
    depends_on:
      - routes-service
      - aq-service
      - users-service
      - db
